-- スキーマ定義。db/index.js が起動時に実行する（CREATE TABLE IF NOT EXISTS なので既存DBには影響しない）。
-- このアプリの肝: 課税/非課税は tax_category で判定する。tax_rate（数値）では判定しない。
--   tax_category … 取引の区分。'STANDARD'（標準課税）/ 'REDUCED'（軽減課税）/ 'EXEMPT'（非課税）
--   tax_rate     … 税額計算に使う税率。0.1 / 0.08 / 0 など。0 でも「非課税」とは限らない点に注意。

-- 税率マスタ（税区分ごとに1行）。items はここを参照する（item * --- 1 tax）。
-- 税率を変えるときはこの1行を UPDATE するだけで、参照する全商品に反映される。
CREATE TABLE IF NOT EXISTS taxes (
  id       INTEGER          PRIMARY KEY,        -- 税ID（seed で明示採番）
  category TEXT             NOT NULL UNIQUE,    -- 税区分: 'STANDARD' / 'REDUCED' / 'EXEMPT'
  rate     DOUBLE PRECISION NOT NULL            -- 税率: 0.1 / 0.08 / 0 など（誤差回避で float8）
);

-- 商品マスタ。税率は持たず、taxes を参照する。
CREATE TABLE IF NOT EXISTS items (
  id       INTEGER PRIMARY KEY,                  -- 商品ID（seed で明示採番）
  name     TEXT    NOT NULL,                     -- 商品名（一覧・検索の対象）
  category TEXT    NOT NULL,                     -- カテゴリ（'食品' '電化製品' など。絞り込みに使う）
  price    INTEGER NOT NULL,                     -- 税抜価格（円。整数で持つ）
  tax_id   INTEGER NOT NULL REFERENCES taxes(id) -- どの税率か（taxes.id）
);

-- 注文（1回の購入 = 1行）
CREATE TABLE IF NOT EXISTS orders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 注文ID（自動採番）
  created_at TEXT    NOT NULL,                                     -- 注文日時（'YYYY-MM-DD HH:MM:SS' 文字列）
  total      INTEGER NOT NULL                                      -- 税込合計（円。明細の税込小計の総和）
);

-- 注文明細（注文の中の商品ごと = 1行）。
-- 購入時点の値をコピーして保存する。後で taxes の税率や商品の価格が変わっても、
-- 過去の注文は購入時の条件で残す（履歴の正しさのため。だから tax_id は参照しない）。
CREATE TABLE IF NOT EXISTS order_details (
  id           INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 明細ID（自動採番）
  order_id     INTEGER          NOT NULL,                  -- どの注文か（orders.id）
  item_id      INTEGER          NOT NULL,                  -- どの商品か（items.id。参考用）
  name         TEXT             NOT NULL,                  -- 購入時の商品名（コピー）
  price        INTEGER          NOT NULL,                  -- 購入時の税抜単価（コピー）
  quantity     INTEGER          NOT NULL,                  -- 数量
  tax_category TEXT             NOT NULL,                  -- 購入時の税区分（コピー。売上集計の判定に使う）
  tax_rate     DOUBLE PRECISION NOT NULL                   -- 購入時の税率（コピー。税額計算に使う）
);
